### ISSUE TITLE
undefined function ssh2_connect

### ISSUE THREAD

**Issue by DatDraggy** [planetteamspeak/ts3phpframework#103] opened 2018-09-02 12:48 UTC
Got the code from here https://github.com/planetteamspeak/ts3phpframework/releases/tag/1.1.33 but still getting that error.
PHP Version 7.0.30-0+deb9u1

`PHP Fatal error:  Uncaught Error: Call to undefined function ssh2_connect() in /var/libraries/TeamSpeak3/Transport/TCP.php:65\nStack trace:\n#0 /var/libraries/TeamSpeak3/Transport/TCP.php(141): TeamSpeak3_Transport_TCP->connect()\n#1 /var/libraries/TeamSpeak3/Adapter/ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine()\n#2 /var/libraries/TeamSpeak3/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn()\n#3 /var/libraries/TeamSpeak3/TeamSpeak3.php(333): TeamSpeak3_Adapter_Abstract->__construct(Array)\n#4 /var/www/x/x.php(6): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))\n#5 {main}\n  thrown in /var/libraries/TeamSpeak3/Transport/TCP.php on line 65
`

**Comment by ronindesign** [comment] 2018-09-02 16:12
Looks like you need to install SSL for PHP.

Not sure what environment you're in, but there is a PECL package as well as others (but assuming Debian from your PHP package):
https://askubuntu.com/questions/866113/ssh2-connect-give-php-fatal-error-uncaught-error-call-to-undefined-function/866126

As another thought, it might be worth adding some tests / checks for environment and compatibility, especially since composer makes this pretty easy.

**Comment by ronindesign** [comment] 2018-09-02 16:57
Hmm, _slower_ is a bit relative and ambiguous. Do you mean slower to connect, slower to load, or slower to run your entire script?

There is some very minor overhead with SSH connection, but you can opt to not use it (there's a TLS query parameter for factory).

Otherwise, we've not made any major changes that would impact runtime performance, so it's hard to say.

If you've noticed something (behavior or task) running quite a bit slower, please explain and we'd love to help troubleshoot and try to reproduce it.

Sometimes issues crop up in different environments of which we're unaware.
We absolutely want to take note of these and do what we can to remedy any slow downs resulting from our implementation!

**Comment by ronindesign** [comment] 2018-09-02 16:59
Closing for now, as initial issue has been resolved.

Please continue to post / reply regarding the slow down issues or open a new issue as you see fit!

Dev note - todo: Update documentation to include ssh module requirement.

**Closed by ronindesign** 2018-09-02 16:59 UTC
Labels: docs, question

**Comment by DatDraggy** [comment] 2018-09-02 17:08
So, when using Port 10011 and no ssh=1, I get a response after about 0.3-0.4 seconds when I reload the page. (Solely the initial request on the file itself)
But when I use Port 10022 and ssh=1, it takes 1.3 seconds

What my script does is it gets the clientList, loops over all clients and selects the one where the webrequester IP matches the clients IP. Then it uses memberOf on that client.

**Comment by ronindesign** [comment] 2018-09-02 17:31
Ah interesting, yeah, it's definitely possible the SSH is affecting runtime then.

SSH encryption is mostly load on CPU, so there definitely could be some throttling happening here.
Still it seems a bit unlikely since overhead should only occur on connect and when transmitting / receiving data (i.e. when encryption is happening).

Maybe you could test / benchmark a few simpler versions of your script:
- minimum: simple connect to server and say login, but don't send any commands / requests for info.
_this will test connection / handshake overhead_
- small: connect and then only make a request for client list
_this will test connection + receiving chunk of encrypted data_

However, unless you have a large number of users, my suspecion is the overhead lies mainly in the connection and handshake setup.

Is your TeamSpeak 3 server running on the same raspberry pi?
If so, as an immediate fix, I would definitely recommend running without SSH/SSL as it is not needed since no data is leaving the system.

Still, this is pretty significant slowdown for what seems to be just the init connection / SSL setup.
So either way, we'll make note of it and see if we can do some testing on our end as well.

**Comment by ronindesign** [comment] 2018-09-02 17:43
Note: I just found post from TS3 team regarding new query system in v3.3.0+.
More than anything, I'm guessing the slowdown is caused by their updated query over SSH.
Ref: https://forum.teamspeak.com/threads/136423-Server-gt-3-3-0-The-New-Query-System

This update has much more likely to be the cause of slowdown than just the SSH connection overhead.
Typically SSL overhead is barely noticeable, so if they changed the backend, that would explain it.

**Comment by DatDraggy** [comment] 2018-09-02 17:56
The TS server is running on a rather powerful VPS and only had ~3 clients.
I edited the script and took out anything relating the query except the factory (hope thats what you meant with minimum). That reduced the loading time via RAW to ~0.25-0.27 and via SSH to ~1.

Atm I can't test it on a bigger server

**Comment by ronindesign** [comment] 2018-09-02 18:31
Hmm that's very interesting, we'll definitely need to test this more.

Yeah, VPS should be plenty of power to test this on.
As per your test, that is still a large difference.

I'll see if I can produce in a few of my testing environments to see if this is really direct result of SSH.
