### ISSUE TITLE
Teamspeak API lost connection

### ISSUE THREAD

**Issue by Mickroz** [planetteamspeak/ts3phpframework#102] opened 2018-09-01 13:01 UTC
i updated my server today to 3.3.1 on linux and got every 6 minutes an error in my log saying:
```
connection to server 'localhost:10011' lost on line 128 in /libraries/TeamSpeak3/Transport/TCP.php
```
then i found out there was a new version out, so i updated the library to version 1.1.32
got the same error on a diff line:
```
connection to server 'localhost:10011' lost on line 131 in /libraries/TeamSpeak3/Transport/TCP.php
```
so i updated to latest and got the same error back:
```
connection to server 'localhost:10011' lost on line 161 in /libraries/TeamSpeak3/Transport/TCP.php
```

this is the part of the bot:
```php
TeamSpeak3::init();

try
{
  /* subscribe to various events */
  TeamSpeak3_Helper_Signal::getInstance()->subscribe("serverqueryConnected", "onConnect");
  TeamSpeak3_Helper_Signal::getInstance()->subscribe("serverqueryWaitTimeout", "onTimeout");
  TeamSpeak3_Helper_Signal::getInstance()->subscribe("notifyLogin", "onLogin");
  TeamSpeak3_Helper_Signal::getInstance()->subscribe("notifyEvent", "onEvent");
  TeamSpeak3_Helper_Signal::getInstance()->subscribe("notifyServerselected", "onSelect");

  /* connect to server, login and get TeamSpeak3_Node_Host object by URI */
  $ts3 = TeamSpeak3::factory("serverquery://". $config['teamspeak']['loginname'] .":". $config['teamspeak']['loginpass'] ."@". $config['teamspeak']['ip'] .":". $config['teamspeak']['queryport'] ."/?server_port=". $config['teamspeak']['serverport'] ."&nickname=". $config['teamspeak']['console_displayname'] ."&blocking=0");

  /* wait for events */
  while(1) $ts3->getAdapter()->wait();
}
catch(Exception $e)
{
	$log->error('console', $e->getCode() . ": " . $e->getMessage() . " on line " . $e->getLine() . " in " . $e->getFile());
	die(udate('Y-m-d H:i:s:u') . "\t[ERROR]\t"  . $e->getCode() . ": " . $e->getMessage() . " on line " . $e->getLine() . " in " . $e->getFile() . "\n");
}
```
running on PHP Version 7.2.5, any ideas?

**Comment by ronindesign** [comment] 2018-09-02 16:37
Thank you for posting all the specifics, including your code.

Hmm, definitely seems like a keepalive issue.

Let me reference my own code examples and also try to reproduce this.

**Comment by ronindesign** [comment] 2018-09-02 16:47
Here's what I've used for keepalive in the past, maybe you can implement something similar:

```php
/**
 * Callback method for 'serverqueryWaitTimeout' signals.
 *
 * @param  integer $seconds
 * @return void
 */
function onTimeout($seconds, TeamSpeak3_Adapter_ServerQuery $adapter)
{ 
  if ($seconds % 20 == 0)
    echo "[SIGNAL] no reply from the server for " . $seconds . " seconds\n";
  
  if($adapter->getQueryLastTimestamp() < time()-300)
  { 
    echo "[INFO]   sending keep-alive command\n";
    
    $adapter->request("clientupdate");
  }
}
```

**Comment by Mickroz** [comment] 2018-09-02 17:15
i got the same:
```php
/**
 * Callback method for 'serverqueryWaitTimeout' signals.
 *
 * @param  integer $seconds
 * @return void
 */
function onTimeout($seconds, TeamSpeak3_Adapter_ServerQuery $adapter)
{
	global $db;
  echo udate('Y-m-d H:i:s:u') . "\t[SIG]\tno reply from the server for " . $seconds . " seconds\n";

  if($adapter->getQueryLastTimestamp() < time()-300)
  {
    echo udate('Y-m-d H:i:s:u') . "\t[INFO]\tsending keep-alive command\n";

    $adapter->request("clientupdate");
	
	echo udate('Y-m-d H:i:s:u') . "\t[INFO]\tkeeping database open\n";
	$db->sql_server_info();
  }
}
```

**Comment by Mickroz** [comment] 2018-09-02 17:32
Im running on a VPS, i never had this issue until i updated my teamspeak server, and the server logs provide no errors that it comes from the teamspeak server, but i had this even on the library 1.1.24 version too.

PHP 7.2.5
Operating System: Arch Linux
Kernel: Linux 4.14.12
Architecture: x86-64

**Comment by ronindesign** [comment] 2018-09-02 17:39
Perfect, thank you for the information!

Yeah, this is very interesting, we've tested a bit with the new TS server, but it's still new so maybe there's something going on underneath that we're unaware of.

We're looking into this and seeing if any other devs are also having issues with keepalive.
Sorry we don't have an immediate solution for you.

Note: I also see some talk on forums regarding the server having new timeout / flood protection config.
https://forum.teamspeak.com/threads/137111-Server-Query-Flood-Protection-too-harsh?p=460881#post460881
https://forum.teamspeak.com/threads/136423-Server-gt-3-3-0-The-New-Query-System

Not sure how relevant it is though,  but maybe it will give you further idea to test instead of being stuck...

**Comment by Mickroz** [comment] 2018-09-02 17:42
Yep, no problem, only thing whats anoying is my pushover notification that my console is restarted, but that i can turn off.

Ill check those topics and see if they are related, thanks.

**Comment by Mickroz** [comment] 2018-09-02 18:13
Its definitly related, if i check my logs, i see that i do 10 queries per second... since you get 10 per login, and that increases by 10 every 3 seconds, it cannot keep up.

**Comment by ronindesign** [comment] 2018-09-02 18:33
Ah perfect, this is great to know, thanks for reporting back.

**Comment by Mickroz** [comment] 2018-09-02 18:46
yeah, it didn't help tho, i set them to 30/1, and still get disconnected.

**Comment by Mickroz** [comment] 2018-09-02 19:14
something changed, i don't know what, but i haven't been disconnected for the last 10 minutes and going.

**Comment by ronindesign** [comment] 2018-09-02 19:17
Maybe persistent anti-flood, i.e. client already throttled (even after you changed setting / restarted server?).

Let us know if your connection remains stable.

I'll make a note to add some tests regarding connection timeout per different server configurations.

**Comment by Mickroz** [comment] 2018-09-02 19:43
yeah, tried restarting the server, didn't work either.
I got this in the logs now:
```
2018-09-02 19:28:44:717686      [ERROR] 0: connection to server 'localhost:10011' lost on line 161 in /libraries/TeamSpeak3/Transport/TCP.php
2018-09-02 19:29:01:894207      [ERROR] 111: Connection refused on line 55 in /libraries/TeamSpeak3/Transport/TCP.php
2018-09-02 19:30:02:318627      [ERROR] 111: Connection refused on line 55 in /libraries/TeamSpeak3/Transport/TCP.php
```

**Comment by ronindesign** [comment] 2018-09-02 19:44
But at least it sounds like it's out past the 6 minutes you were experiencing before?

So maybe this indicates the issue is on a lower level.

**Comment by Mickroz** [comment] 2018-09-02 20:01
yeah, i don't know, it was 12 minutes before, and now it disconnects every 6 minutes again.
tried connecting on localhost and 127.0.0.1, that gave the 111 errors, so that didn't work, now im testing connecting on the ip address, which is the same the script connects from, and see if that helps.

**Comment by Mickroz** [comment] 2018-09-02 21:32
Didn't work either, still losing connection, so im out of ideas.

**Comment by ronindesign** [comment] 2018-09-02 21:52
That's frustrating, I wonder if there is something else causing the connection to drop or block keepalive requests... that's pretty strange... and I haven't been able to reproduce it myself yet...

**Comment by Mickroz** [comment] 2018-09-02 22:02
Yep, even tried to throttle my other scripts, but that didn't work either, will try to turn them off, and just let the console run.

**Comment by Mickroz** [comment] 2018-09-02 23:45
That didn't help either, still losing connection after 6 minutes.

**Comment by Mickroz** [comment] 2018-09-03 01:32
You know what, im not seeing the keep alive command in the logs, i editted my file with your code for the signal, and it shows in the log even up to 240 seconds...
So there is something wrong with my code then?

**Comment by Mickroz** [comment] 2018-09-03 05:46
I changed the keep alive time to 150 and that seems to fix it, its running without losing connection since my last post.
So what changed in the new teamspeak server that could cause this?

**Comment by ronindesign** [comment] 2018-09-03 15:16
That's a very good question. I don't see anything in their changelog or on forums regarding a change in timeout for the server...

**Comment by Mickroz** [comment] 2018-09-03 15:48
ok, it is still running, and i upped it to 250 now, cannot find anything in the changelog either, so i still think it has something to do with the new flooding protection, since i check with cronjob every minute if the console still runs + 300 seconds for the flood/keep alive is 6 minutes?

**Comment by ronindesign** [comment] 2018-09-03 20:09
Yeah, so the server query timeout has always been 10 minutes [[1][1]].
In my example keepalive callback I just select 6 minutes to be on safe side.
_Technically_ you should be able to set this to 9min 59sec...

Regarding flood protection, the limits there are completely irrespective of timeout.
The limits are specified in the previously linked thread [[2][2]].

So the conflict could arise if you've sent a lot of commands and are now blocked for flooding.
Then, when you go to send keepalive, you might also be blocked, which will then cause timeout due to inactivity.

Also, just to reiterate, if you can correctly whitelist your console's source IP (localhost, static IP, etc), then flood protection _should not_ block your console's requests.

So you may want to first make sure your whitelisting is correct and working before troubleshooting keepalive.

[1]: https://forum.teamspeak.com/threads/130705-How-long-does-it-take-till-Server-Query-Timeout
[2]: https://forum.teamspeak.com/threads/136423-Server-gt-3-3-0-The-New-Query-System

**Comment by Mickroz** [comment] 2018-09-03 21:33
yeah, but when i sent a lot of commands, i should be blocked for flooding even after the keepalive?
the seconds signal isn't going higher then max 60 seconds now, and i set it back to 300 to test.

As for the whitelist, the teamspeak log says it has updated the whitelist with the ip's appointed to my vps server, and localhost ip, so that seems to work, don't how to test that?
hmm still losing connection, will try 290 now.

In the first topic posted, there was someone else who got the bot disconnected every 5 minutes, which was whitelisted.

Is there anyway i can log what the server is returning as an answer when i flood with the api?

**Comment by Mickroz** [comment] 2018-09-04 06:09
lowered it back to 250, will keep it at that for the moment, as it seems te be stable, 290 was a bit unstable, but not as unstable as 300.

**Comment by Shad86** [comment] 2018-09-06 17:02
They changed the Standart timeout to 5 minutes btw :) - tested only with ssh2 connection but i think this standart counts for both.

**Comment by ronindesign** [comment] 2018-09-06 17:54
Thanks for the heads up @Shad86, we'll note this in the documentation and add a couple tests for it.

Closing this for now as it seems to be resolved. Feel free to comment if still having trouble.

**Closed by ronindesign** 2018-09-06 17:54 UTC
