### ISSUE TITLE
TeamSpeak3_Adapter_ServerQuery_Exception: file transfer limit reached

### ISSUE THREAD

**Issue by LaocheXe** [planetteamspeak/ts3phpframework#81] opened 2018-05-18 02:37 UTC
Fatal error: Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: file transfer limit reached in /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Node/Server.php:1713 Stack trace: #0 /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Viewer/Html.php(570): TeamSpeak3_Node_Server->transferInitDownload(62189, 0, Object(TeamSpeak3_Helper_String)) #1 /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Viewer/Html.php(406): TeamSpeak3_Viewer_Html->getSuffixIconClient() #2 /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Viewer/Html.php(140): TeamSpeak3_Viewer_Html->getSuffixIcon() #3 /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Node/Abstract.php(206): TeamSpeak3_Viewer_Html->fetchObject(Object(TeamSpeak3_Node_Client), Array) #4 /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/viewers/ts3/ts3.php(71): TeamSpeak3_Node_Abstract->getViewer(Object(TeamSpeak3_Viewer_Html)) #5 {main} thrown in /usr/www/taskforce13tsw/501st/e107/e107_plugins/voice/libraries/TeamSpeak3/Node/Server.php on line 1713

**Comment by ronindesign** [comment] 2018-05-18 17:50
As you can see:
```php
$download = $this->execute("ftinitdownload", array("clientftfid" => $clientftfid, "cid" => $cid, "name" => $name, "cpw" => $cpw, "seekpos" => $seekpos))->toList();

if(array_key_exists("status", $download) && $download["status"] != 0x00)
{
  throw new TeamSpeak3_Adapter_ServerQuery_Exception($download["msg"], 
$download["status"]);
}
```

There is no issue with the framework, your TeamSpeak server is returning this error, probably as a result of file transfer settings.

Please feel free to add additional information for further assistance.
Closing for now as this seems to be a case of expected behavior for file transfer limit configuration.

**Closed by ronindesign** 2018-05-18 17:50 UTC
