### ISSUE TITLE
privilegeKeyCreate returns error

### ISSUE THREAD

**Issue by vanlueckn** [planetteamspeak/ts3phpframework#161] opened 2021-05-25 21:08 UTC
```php
$arr_ServerGroup = $ts3_VirtualServer->serverGroupGetById((int) $group);
// create the privilege key
$ts3_PrivilegeKey = $arr_ServerGroup->privilegeKeyCreate()->toString();
```
Accessing the server group does work properly. privilegeKeyCreate throws the following error:

`TeamSpeak3_Adapter_ServerQuery_Exception: invalid parameter in file F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Adapter\ServerQuery\Reply.php on line 316`

I am currently not able to find the cause for the error. I am using PHP 8.0.0. Getting server groups and creating virtual servers does work properly. 

Full Error Stack:

```#0 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Adapter\ServerQuery\Reply.php(88): TeamSpeak3_Adapter_ServerQuery_Reply-&gt;fetchError(Object(TeamSpeak3_Helper_String))
#1 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Adapter\ServerQuery.php(140): TeamSpeak3_Adapter_ServerQuery_Reply-&gt;__construct(Array, 'privilegekeyadd...', Object(TeamSpeak3_Node_Host), true)
#2 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Abstract.php(70): TeamSpeak3_Adapter_ServerQuery-&gt;request('privilegekeyadd...', true)
#3 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Server.php(87): TeamSpeak3_Node_Abstract-&gt;request('privilegekeyadd...', true)
#4 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Abstract.php(94): TeamSpeak3_Node_Server-&gt;request('privilegekeyadd...')
#5 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Server.php(2038): TeamSpeak3_Node_Abstract-&gt;execute('privilegekeyadd', Array)
#6 F:\Projekte\techkings-webseite\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Servergroup.php(199): TeamSpeak3_Node_Server-&gt;privilegeKeyCreate(0, 3, 0, NULL, NULL)
#7 F:\Projekte\techkings-webseite\app\Http\Controllers\ServiceController.php(1067): TeamSpeak3_Node_Servergroup-&gt;privilegeKeyCreate()
#8 F:\Projekte\techkings-webseite\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\ServiceController-&gt;createTeamspeakKey(935, '3')```

**Comment by Sebi94nbg** [comment] 2023-02-18 23:58
This issue seems to be fixed on the current code base of the `dev` branch. I can't reproduce it anymore.

Maybe PHP 8.x support wasn't properly implemented back then in May 2021.

`->toString()` is not necessary (anymore) as the function already returns a `string`.

```php
$servergroup_id = 104;
$arr_ServerGroup = $virtualserver->serverGroupGetById((int) $servergroup_id);
$ts3_PrivilegeKey = $arr_ServerGroup->privilegeKeyCreate();
echo "Successfully created the following priv key: $ts3_PrivilegeKey";

$arr_ServerGroup = $virtualserver->serverGroupGetByName("VIP");
$ts3_PrivilegeKey = $arr_ServerGroup->privilegeKeyCreate();
echo "Successfully created the following priv key: $ts3_PrivilegeKey";
```

```shell
Successfully created the following priv key: 7TLUFdZGm...iVHzjS
Successfully created the following priv key: ny1OfpAk4...AOcwj+
```

**Closed by Sebi94nbg** 2023-02-18 23:58 UTC
